### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by FredChenEcon** [ProjectKiev/ReportOne#2]
"What things need to be done to complete this project successfully".

See software engineering lecture for further explanation.

- List of goals, using goal-oriented capture, as talked about in lecture
- System boundaries
- Feasibility
- Categorise
- Priorities
- **Planned completion dates**

**Comment by ArnoldLIULJ** [comment]
System boundaries:
1. stakeholders: us, supervisor, testers and users
2. online. webpage
frontend:
-software: browser.
-hardware: desktop.
backend:
-software: pytorch, python
-hardware: cpu

**Comment by ArnoldLIULJ** [comment]
Feasibility:
1. tech skills: machine learning, python(pytorch), web development
2. soft skills: leadership, communication, teamwork

Based on the previous research

**Comment by ArnoldLIULJ** [comment]
Development Strategy:

1. version control: git -> use branch, pull request for reviewing and integrating our work, as well as the issue tracking.
2. coordinations: scrum, slack, GitHub
3.  3 pairs -> each for one mode(rating/image/text)
