### ISSUE TITLE
Development Strategy

### ISSUE THREAD

**Issue by FredChenEcon** [ProjectKiev/ReportOne#4]
"How we plan to go about achieving goals in Project Requirements".

- Version control system (git)
- Coordination (scrum)
- Division of labour

**Comment by ArnoldLIULJ** [comment]
Development Strategy:

version control: git -> use branch, pull request for reviewing and integrating our work, as well as the issue tracking.
coordinations: scrum, slack, GitHub
3 pairs -> each for one mode(rating/image/text)
